---
title: "test updates"
output: html_notebook
---


```{r}
computeNeighboursDelaunayOrig = function(centroids){
    
    ##compute delaunay triangulation
    delaunay = tri.mesh(centroids[,1], centroids[,2])
    
    ##extract triangles from results dataframe
    triangles = delaunay$trlist
    
    results = matrix(nrow = 0, ncol = 2)
    cellNames = rownames(centroids)
    
    ##convert triangle indices to cell names
    triangles[,1] = cellNames[as.numeric(triangles[,1])]
    triangles[,2] = cellNames[as.numeric(triangles[,2])]
    triangles[,3] = cellNames[as.numeric(triangles[,3])]
    
    ##create neighbour list
    for (i in 1:nrow(triangles)){
        results = rbind(results,sort(c(triangles[i,1],triangles[i,2])))
        results = rbind(results,sort(c(triangles[i,1],triangles[i,3])))
        results = rbind(results,sort(c(triangles[i,2],triangles[i,3])))
    }
    
    ##remove duplicate edges
    results = unique(results)
    
    ## Convert to data.frame and name as nodeA, nodeB:
    results = as.data.frame(results)
    names(results) = c('nodeA','nodeB')
    
    return(results)
}

```

```{r}
delaunayNeighbours = computeNeighboursDelaunay(centroids)
delaunayNeighboursOrig = computeNeighboursDelaunayOrig(centroids)
```


```{r}
dim(delaunayNeighbours)
dim(delaunayNeighboursOrig)
```

```{r}
head(delaunayNeighbours[order(delaunayNeighbours$nodeA,delaunayNeighbours$nodeB),], n = 100)
```
```{r}
head(delaunayNeighboursOrig[order(delaunayNeighboursOrig$nodeA,delaunayNeighboursOrig$nodeB),], n = 100)
```

`

```{r}
delaunayNeighboursOrig[order(delaunayNeighboursOrig$nodeA,delaunayNeighboursOrig$nodeB),] == delaunayNeighbours[order(delaunayNeighbours$nodeA,delaunayNeighbours$nodeB),]
```


```{r}
save(delaunayNeighboursOrig,file = "../data/delaunayNeighboursOrig.rda")
```

```{r}
delaunayNeighboursOrigR = delaunayNeighboursOrig
names(delaunayNeighboursOrigR) = c("nodeB","nodeA")
delaunayNeighboursOrig = rbind(delaunayNeighboursOrig,delaunayNeighboursOrigR[,c(2,1)])
```

```{r}
delaunayNeighboursR = delaunayNeighbours
names(delaunayNeighboursR) = c("nodeB","nodeA")
delaunayNeighbours = rbind(delaunayNeighbours,delaunayNeighboursR[,c(2,1)])
```


```{r}
combined = paste0(delaunayNeighbours$nodeA, "_", delaunayNeighbours$nodeB)
combined_orig = paste0(delaunayNeighboursOrig$nodeA, "_", delaunayNeighboursOrig$nodeB)
```


```{r}
dim(delaunayNeighboursOrig)
```

```{r}
dim(delaunayNeighbours)
```

```{r}
unique(combined[!(combined %in% combined_orig)])
```


```{r}
unique(combined_orig[!(combined_orig %in% combined)])
```

```{r}
computeNeighbourhoodByCTMatrixOrig = function(neighbourhoods, cellTypes){

     cellNames = names(cellTypes)
     neighbourhoodByCT = matrix(nrow = 0, ncol = length(levels(cellTypes)))

     for (neighbourhood in neighbourhoods){
         neighbourhoodByCT = rbind(neighbourhoodByCT,table(cellTypes[neighbourhood]))
     }
     rownames(neighbourhoodByCT) = names(neighbourhoods)

     return(neighbourhoodByCT)
}
```


```{r}
neighbourhoods = computeNeighbourhoods(delaunayNeighbours,
names(clusters))

neighbourhoodbyCTmatrixOrig = computeNeighbourhoodByCTMatrixOrig(neighbourhoods, 
                                                         clusters)
```

```{r}
neighbourhoodbyCTmatrix = computeNeighbourhoodByCTMatrix(delaunayNeighbours,clusters) 
```

```{r}
sum(neighbourhoodbyCTmatrix == neighbourhoodbyCTmatrixOrig)
```

```{r}
dim(neighbourhoodbyCTmatrix)
```

```{r}
36553 * 24
```

```{r}
cellTypesPerCellTypeMatrixOrig = function(nbhdByCellType,seurat_clusters)
{
    clusters = unique(seurat_clusters)
    clusters = clusters[order(clusters)]
    N = length(clusters)
    M = matrix(0,nrow=N,ncol=N)
    Clusters = as.character(clusters)
    rownames(M) = Clusters
    colnames(M) = Clusters

    for(cell in rownames(nbhdByCellType))
    {
        type = as.character(seurat_clusters[cell])
        M[type,] = M[type,] + nbhdByCellType[cell,]
    }

    rowTotals = rowSums(M)
    MM = M
    for(i in 1:nrow(M))
        MM[i,] = MM[i,]  / rowTotals[i]

    return(MM)
}
```


```{r}
cellTypeMatrixOrig = cellTypesPerCellTypeMatrixOrig(neighbourhoodbyCTmatrix,clusters)
```

```{r}
cellTypeMatrix = cellTypesPerCellTypeMatrix(neighbourhoodbyCTmatrix,clusters)
```

```{r}
dim(cellTypeMatrix)
```
```{r}
cellTypesPerCellTypeGraphFromMatrix(cellTypeMatrix)
```
```{r}
cellTypesPerCellTypeGraph(neighbourhoodbyCTmatrix, clusters)
```

